name: Reloader
description: Reload or disable plugins at will
version: 3.4.0

author: jmgr2007

main: 'me.jmgr2007.Reloader.Reloader'

commands:
  reloader:
    description: index command for Reloader
    usage: '/reloader for help'

permissions:
  reloader.reload:
    description: Permission to reload plugins
    default: op
  reloader.list:
    description: see reloader's plugins list
    default: op
